<a href="https://colab.research.google.com/github/jung0228/ML/blob/main/%EC%A3%BC%EC%8B%9D_%EC%9E%AC%EB%AC%B4%EC%9E%AC%ED%91%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("00126380_annual.xlsx")

In [ ]:
df

    Unnamed: 0  ...         20171231
0          NaN  ...      ('연결재무제표',)
1          NaN  ...              NaN
2          0.0  ...  146982464000000
3          1.0  ...   30545130000000
4          2.0  ...   49447696000000
5          3.0  ...              NaN
6          4.0  ...              NaN
7          5.0  ...   27695995000000
8          6.0  ...    4108961000000
9          7.0  ...    3835219000000
10         8.0  ...   24983355000000
11         9.0  ...    1421060000000
12        10.0  ...              NaN
13        11.0  ...  154769626000000
14        12.0  ...              NaN
15        13.0  ...              NaN
16        14.0  ...              NaN
17        15.0  ...    6802351000000
18        16.0  ...  111665648000000
19        17.0  ...   14760483000000
20        18.0  ...     825892000000
21        19.0  ...    5061687000000
22        20.0  ...    7794634000000
23        21.0  ...  301752090000000
24        22.0  ...   67175114000000
25        23.0  ...    9083907000000
26        24.0  ...   15767619000000
27        25.0  ...   13899633000000
28        26.0  ...    1249174000000
29        27.0  ...     793582000000
30        28.0  ...   13996273000000
31        29.0  ...    7408348000000
32        30.0  ...     278619000000
33        31.0  ...    4294820000000
34        32.0  ...     403139000000
35        33.0  ...              NaN
36        34.0  ...   20085548000000
37        35.0  ...     953361000000
38        36.0  ...    1814446000000
39        37.0  ...    2043729000000
40        38.0  ...     389922000000
41        39.0  ...   11710781000000
42        40.0  ...     464324000000
43        41.0  ...    2708985000000
44        42.0  ...   87260662000000
45        43.0  ...  207213416000000
46        44.0  ...     897514000000
47        45.0  ...     119467000000
48        46.0  ...     778047000000
49        47.0  ...    4403893000000
50        48.0  ...  215811200000000
51        49.0  ...  -13899191000000
52        50.0  ...              NaN
53        51.0  ...    7278012000000
54        52.0  ...  214491428000000
55        53.0  ...  301752090000000

[56 rows x 13 columns]

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (3.0.9)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)

In [ ]:
from openpyxl import Workbook, load_workbook
import pandas as pd

In [ ]:
file = 'samung_10years.xlsx'

wb = load_workbook(file)

ws_bs = wb['Data_bs']

y_list = []
c= 10
while ws_bs.cell(2, c).value != None:
  y = ws_bs.cell(1, c).value
  if y[:1] == '2':
    y_list.append(y)
  c += 1

bs_items = ['ifrs-full_CurrentAssets']

df_list = []
for bs_item in bs_items:
  temp_list = []
  r = 4
  while ws_bs.cell(r, 2).value != None:
    if ws_bs.cell(r,2).value == bs_item:
      item = ws_bs.cell(r, 3).value
      c = 10
      while ws_bs.cell(1, c).value != None:
        temp_list.append(ws_bs.cell(r, c).value)
        c += 1
    r += 1
  df = pd.DataFrame({item : temp_list}, index = y_list)
  df_list.append(df)

total_df = pd.concat(df_list, axis=1)
total_df = total_df.transpose()

print(total_df)

             20201231         20191231  ...        20090101        20081231
유동자산  198215579000000  181385260000000  ...  40110089000000  48968556000000

[1 rows x 14 columns]

In [ ]:
total_df